spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '@Ironmzx1998'
    url: jdbc:mysql://127.0.0.1:3306/mall?characterEncoding=utf-8&useSSL=false
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#    console log config (Maybe in the future, need to output the log into the file)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
logging:
    pattern:
      console: "[%thread] %-5level %logger{36} - %msg%n"
server:
  servlet:
    session:
#      2 mins
      timeout: 120